# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QStory
                                 A QGIS plugin
 Build a story upon a Web Map
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-08-10
        copyright            : (C) 2019 by Klas Karlsson
        email                : klas.karlsson@geosupportsystem.se
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load QStory class from file QStory.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .qstory import QStory
    return QStory(iface)
